/*
 * generated by Xtext
 */
package hu.bme.mit.rnd.behavior.text.ui.contentassist

import hu.bme.mit.rnd.behavior.text.ui.contentassist.AbstractBehaviorDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class BehaviorDSLProposalProvider extends AbstractBehaviorDSLProposalProvider {
}
