/*
 * generated by Xtext
 */
package hu.bme.mit.rnd.behavior.text.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BehaviorDSLUiModule extends hu.bme.mit.rnd.behavior.text.ui.AbstractBehaviorDSLUiModule {
	public BehaviorDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
