/**
 * generated by Xtext
 */
package hu.bme.mit.rnd.behavior.text.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class BehaviorDSLQuickfixProvider extends DefaultQuickfixProvider {
}
