/*
* generated by Xtext
*/
package hu.bme.mit.rnd.behavior.text;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class BehaviorDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return hu.bme.mit.rnd.behavior.text.ui.internal.BehaviorDSLActivator.getInstance().getInjector("hu.bme.mit.rnd.behavior.text.BehaviorDSL");
	}
	
}
