/**
 * generated by Xtext
 */
package hu.bme.mit.rnd.behavior.text.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
@SuppressWarnings("all")
public class BehaviorDSLOutlineTreeProvider extends DefaultOutlineTreeProvider {
}
