/*
 * generated by Xtext
 */
package hu.bme.mit.rnd.behavior.text;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BehaviorDSLRuntimeModule extends hu.bme.mit.rnd.behavior.text.AbstractBehaviorDSLRuntimeModule {

}
