/*
* generated by Xtext
*/
package hu.bme.mit.rnd.behavior.text;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BehaviorDSLStandaloneSetup extends BehaviorDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new BehaviorDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

