/*
 * generated by Xtext
 */
package hu.bme.mit.rnd.behavior.text.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import hu.bme.mit.rnd.behavior.text.ui.internal.BehaviorDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BehaviorDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BehaviorDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BehaviorDSLActivator.getInstance().getInjector(BehaviorDSLActivator.HU_BME_MIT_RND_BEHAVIOR_TEXT_BEHAVIORDSL);
	}
	
}
