/**
 * generated by Xtext
 */
package hu.bme.mit.rnd.behavior.text.validation;

import hu.bme.mit.rnd.behavior.text.validation.AbstractBehaviorDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class BehaviorDSLValidator extends AbstractBehaviorDSLValidator {
}
