/*
* generated by Xtext
*/
package hu.bme.mit.rnd.behavior.text.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import hu.bme.mit.rnd.behavior.text.services.BehaviorDSLGrammarAccess;

public class BehaviorDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BehaviorDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected hu.bme.mit.rnd.behavior.text.parser.antlr.internal.InternalBehaviorDSLParser createParser(XtextTokenStream stream) {
		return new hu.bme.mit.rnd.behavior.text.parser.antlr.internal.InternalBehaviorDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "System";
	}
	
	public BehaviorDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BehaviorDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
