/*
* generated by Xtext
*/
package hu.bme.mit.rnd.behavior.text.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BehaviorDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("hu/bme/mit/rnd/behavior/text/parser/antlr/internal/InternalBehaviorDSL.tokens");
	}
}
